name: HealMind CI Pipeline

on:
  push:
    branches:
      - devops-latest

  workflow_dispatch:

concurrency:
  group: devops-latest
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  docker-build:

    name: Build, Scan & Push Docker Image

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        app:
          - name: frontend
            context: ./Front_End
            dockerfile: ./Front_End/Dockerfile
            image: healmind-frontend

          - name: backend
            context: ./Back_End
            dockerfile: ./Back_End/Dockerfile
            image: healmind-backend

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v7
        # edited
        with:
          fetch-depth: 0 # Required for Gitleaks to scan the full history

      # Detect Hardcoded Secrets
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Static Application Security Testing
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          
          cache-dependency-path: |
            Front_End/package-lock.json
            Back_End/package-lock.json

      # Install Frontend Dependencies
      - name: Install Frontend Dependencies
        if: matrix.app.name == 'frontend'
        working-directory: ./Front_End
        run: npm ci

      # Frontend Dependency Scan
      - name: Frontend Dependency Scan
        if: matrix.app.name == 'frontend'
        working-directory: ./Front_End
        run: npm audit --audit-level=high

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        if: matrix.app.name == 'backend'
        working-directory: ./Back_End
        run: npm ci

      # Backend Dependency Scan
      - name: Backend Dependency Scan
        if: matrix.app.name == 'backend'
        working-directory: ./Back_End
        run: npm audit --audit-level=high

      # edited
      - name: Build Docker Image Locally
        run: docker build -t my-secure-app:latest.

        - name: Trivy Image Scan
          uses: aquasecurity/trivy-action@master
          with:
          image-ref: "my-secure-app:latest"
          format: "table"
          exit-code: "1" # Fails the pipeline if critical issues are found
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
# -----------------------------------
      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build Docker Image
      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.app.context }}
          file: ${{ matrix.app.dockerfile }}
          load: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app.image }}:latest

      # # Scan Docker Image
      # - name: Scan Docker Image with Trivy
      #   uses: aquasecurity/trivy-action@v0.36.0
      #   with:
      #     image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app.image }}:latest
      #     format: table
      #     exit-code: 1
      #     severity: HIGH,CRITICAL

      # Push Docker Image
      - name: Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.app.context }}
          file: ${{ matrix.app.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app.image }}:latest
